---
- name: Install tmux build deps via apt
  apt:
    name:
      - libevent-dev
      - libncurses-dev
      - pkg-config
  become: true

- name: check if tmux installed
  stat:
    path: /usr/local/bin/tmux
  register: tmux

- name: Download tmux {{ TMUX_VERSION }} to /tmp/tmux
  unarchive:
    dest: /tmp
    remote_src: true
    src: https://github.com/tmux/tmux/releases/download/{{ TMUX_VERSION }}/tmux-{{ TMUX_VERSION }}.tar.gz
  when: not tmux.stat.exists

- name: Run /tmp/tmux-{{ TMUX_VERSION }}/configure
  command: sh ./configure
  args:
    chdir: /tmp/tmux-{{ TMUX_VERSION }}
  when: not tmux.stat.exists

- name: Run make in /tmp/tmux-{{ TMUX_VERSION }}
  make:
    chdir: /tmp/tmux-{{ TMUX_VERSION }}
  when: not tmux.stat.exists

- name: Run make install to install tmux
  make:
    chdir: /tmp/tmux-{{ TMUX_VERSION }}
    target: install
  become: true
  when: not tmux.stat.exists

- name: Cleanup /tmp/tmux-{{ TMUX_VERSION }}
  file:
    path: /tmp/tmux-{{ TMUX_VERSION }}/
    state: absent

- name: Install xsel so tmux-yank works
  apt:
    name: xsel=*
  become: true
