---
sudo: required
language: python
services:
  - docker
matrix:
  include:
  - env: ROLE=bat
  - env: ROLE=fd
  - env: ROLE=fzf
  - env: ROLE=git
  - env: ROLE=gitk
  - env: ROLE=hub
  - env: ROLE=nvm
  - env: ROLE=packages-system
  - env: ROLE=tmux
  - env: ROLE=vim
  - env: ROLE=zsh
before_install:
  - sudo apt-get -qq update
  - cd ./$ROLE
install:
  - pip install molecule docker
script:
  - molecule test
