---
sudo: required
language: python
services:
  - docker
matrix:
  fast_finish: true
  include:
    - env: ROLE=fzf
    - env: ROLE=git
    - env: ROLE=hub
    - env: ROLE=nvm
    - env: ROLE=packages-system
    - env: ROLE=tmux
    - env: ROLE=vim
    - env: ROLE=zsh
  allow_failures:
    - env: ROLE=zsh
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule docker
script:
  - make test
