---
# This playbook sets up a dev environment.

- name: set up dev env
  hosts: all
  roles:
    - {role: fzf, tags: ['fzf']}
    - {role: git, tags: ['git']}
    - {role: go, tags: ['go']}
    - {role: hub, tags: ['hub']}
    - {role: nvm, tags: ['nvm']}
    - {role: packages_system, tags: ['packages_system']}
    - {role: tmux, tags: ['tmux']}
    - {role: vim, tags: ['vim']}
    - {role: zsh, tags: ['zsh']}
