---
- name: Install package signing keys via download
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ apt_signing_keys }}"

#- name: Install signing keys from ubuntu keyserver
#  apt_key:
#    keyserver: pool.sks-keyservers.net
#    id: "{{ item }}"
#    state: present
#  with_items: "{{ ubuntu_keyserver_keys }}"

- name: Add package sources
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repositories }}"

- name: Add ppa repositories
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ ppa_repositories }}"

#- name: Update apt cache
#  apt:
#    cache_valid_time: 3600
#  changed_when: false

- name: Remove packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apt_packages_to_remove }}"

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  when: update_dist_packages == True

- name: "Install packages"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: "{{ apt_packages }}"

- name: Install debs
  apt:
    deb: "{{ item }}"
  with_items: "{{ debs }}"
  when: install_deb_packages == True
  check_mode: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
