---
- import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy .vimrc to ~ directory
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: Create ~/.vim/autoload directory
  file:
    path: ~/.vim/autoload
    state: directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Install vim plugins
  command: vim +PlugInstall +qa
  args:
    creates: ~/.vim/plugged
