---
- name: Check if nvm installed
  stat:
    path: ~/.nvm/nvm.sh
  register: nvm

- name: Download nvm install script to /tmp
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh
    dest: /tmp/nvm-install.sh
  when: not nvm.stat.exists

- name: Install nvm
  command: bash /tmp/nvm-install.sh
  when: not nvm.stat.exists

- name: Check if node is installed
  find:
    file_type: directory
    pattern: 'v10.15.0'
    paths: ~/.nvm/versions/node/
  register: node_versions

- name: Install Node
  command: bash -c "source ~/.nvm/nvm.sh && nvm install 10.15.0"
  when: node_versions.matched == 0

- name: Install global npm packages
  npm:
    global: true
    name: "{{ item }}"
    state: present
  with_items:
    - diff-so-fancy
  environment:
    PATH: "{{ ansible_env.HOME}}/.nvm/versions/node/v10.15.0/bin:{{ ansible_env.PATH }}"
