---
- name: Check if nvm installed
  stat:
    path: ~/.nvm/nvm.sh
  register: nvm

- name: Download nvm install script to /tmp
  get_url:
    dest: /tmp/nvm-install.sh
    url: https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh
  when: not nvm.stat.exists

- name: Install nvm
  command: bash /tmp/nvm-install.sh
  when: not nvm.stat.exists

- name: Setup default global packages
  copy:
    backup: true
    dest: ~/.nvm/default-packages
    src: default-packages

- name: Check if node is installed
  find:
    file_type: directory
    paths: ~/.nvm/versions/node/
    pattern: 'v10.15.0'
  register: node_versions

- name: Install Node
  command: bash -c "source ~/.nvm/nvm.sh && nvm install 10.15.0"
  when: node_versions.matched == 0
