---
- import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'

- name: Previous go version
  shell: |
    set -o pipefail

    if command -v /usr/local/go/bin/go > /dev/null ; then
      /usr/local/go/bin/go version | sed 's/.*go\(.*\) .*/\1/'
    fi
  args:
    executable: /bin/bash
  register: go_version
  changed_when: false

- name: Delete previous version of go to prevent corrupt go installation
  file:
    path: /usr/local/go
    state: absent
  when: go_version.stdout|default('None') != GO_VERSION
  become: true

- name: Download and extract go to /usr/local/go
  unarchive:
    dest: /usr/local/
    remote_src: true
    src: https://dl.google.com/go/go{{ GO_VERSION }}.{{ ansible_system }}-amd64.tar.gz
  when: go_version.stdout|default('None') != GO_VERSION
  become: true
