---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -ex
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu-2004
    image: ubuntu:20.04
  - name: ubuntu-2104
    image: ubuntu:21.04
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
scenario:
  name: default
verifier:
  name: testinfra
