---
- name: Add git ppa to install latest git
  apt_repository:
    filename: git
    repo: ppa:git-core/ppa
  become: true

- name: Install git and gitk via apt
  apt:
    name:
      - git
      - gitk
  become: true
