---
- name: Install gnupg2 so git ppa can be added
  apt:
    name:
      - gnupg2
  become: true

- name: Install vim via apt
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - vim=*
      - vim-gui-common=*
  become: true
