---
- import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy .vimrc to ~ directory
  copy:
    backup: true
    dest: ~/.vimrc
    src: vimrc
    mode: '0644'
  notify:
    - Install vim plugins

- name: Create ~/.vim/autoload directory
  file:
    path: ~/.vim/autoload
    state: directory
    mode: '0755'

- name: Install vim-plug
  get_url:
    dest: ~/.vim/autoload/plug.vim
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
