---
- import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'

- name: Clone fzf repository
  git:
    dest: ~/.fzf
    repo: https://github.com/junegunn/fzf
    version: "{{ FZF_VERSION }}"

- name: Download and extract fzf to ~/.fzf/bin/fzf
  unarchive:
    dest: ~/.fzf/bin/
    remote_src: true
    src: https://github.com/junegunn/fzf-bin/releases/download/{{ FZF_VERSION }}/fzf-{{ FZF_VERSION }}-{{ ansible_system }}_amd64.tgz
