---
- name: Install packages via apt
  apt:
    name:
      - httpie
      - jq
      - silversearcher-ag
      - tree
  become: true

- name: Install bat via .deb from github release
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v{{ BAT_VERSION }}/bat_{{ BAT_VERSION }}_amd64.deb
  become: true

- name: Install fd via .deb from github release
  apt:
    deb: https://github.com/sharkdp/fd/releases/download/v{{ FD_VERSION }}/fd_{{ FD_VERSION }}_amd64.deb
  become: true
