---
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Create ~/.zfunctions directory
  file:
    path: ~/.zfunctions
    state: directory

- name: Install prompt_pure_setup zfunction
  get_url:
    dest: ~/.zfunctions/prompt_pure_setup
    url: https://raw.githubusercontent.com/sindresorhus/pure/master/pure.zsh

- name: Install async zfunction
  get_url:
    dest: ~/.zfunctions/async
    url: https://raw.githubusercontent.com/sindresorhus/pure/master/async.zsh

- name: Create ~/.zscripts directory
  file:
    path: ~/.zscripts
    state: directory

- name: Install z tool
  get_url:
    dest: ~/.zscripts/z.sh
    url: https://raw.githubusercontent.com/rupa/z/master/z.sh

- name: Clone zsh-syntax-highlighting
  git:
    dest: ~/.zscripts/zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    version: master

- name: Copy zshrc ~/.zshrc
  copy:
    dest: ~/.zshrc
    src: zshrc

- name: Change default shell to /bin/zsh
  command: "chsh -s /bin/zsh {{ ansible_user_id }}"
  become: true
  when: ansible_user_shell != '/bin/zsh'
