---
- import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: copy .gitconfig to ~ directory
  copy:
    src: gitconfig
    dest: ~/.gitconfig
