---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -ex
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu-2004
    image: ubuntu:20.04
  - name: ubuntu-1804
    image: ubuntu:18.04
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
