---
- name: Add vim apt repo to install latest vim
  apt_repository:
    filename: vim
    repo: ppa:jonathonf/vim
  become: true

- name: Install vim via apt
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - vim=*
      - vim-gui-common=*
  become: true
