---
name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        role:
          - fzf
          - git
          - go
          - hub
          - nvm
          - packages_system
          - tmux
          - vim
          - zsh
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - env:
          LC_ALL: "C.UTF-8"
          LANG: "C.UTF-8"
          ROLE: "${{ matrix.role }}"
        run: |
          sudo apt install python3.8 python3.8-dev --yes
          python3.8 --version
          python3.8 -m pip install pipenv
          export PATH=$HOME/.local/bin/:$PATH
          pipenv sync --dev
          pipenv run make ${ROLE}
...
